### ISSUE TITLE
Mangakakalot Genres not showing

### ISSUE THREAD

**Issue by getBoolean** [getBoolean/extensions-beta#5]
The manga genres do not show under the description in Mangakakalot

**Comment by ConradWeiser** [comment]
While briefly reviewing your logic at:
https://github.com/getBoolean/extensions-beta/blob/7975bc25bdf5923d8df4196da8a201db55392de4/src/Mangakakalot/Mangakakalot.ts#L118

The logic you've used looks rather similar to other sources such as MangaLife, which likely means that we can rule out some of the Typescript quirks (Ie: Having to use `createTag({..})` and such)

My suggestion is to use the Mocha tests. You can place breakpoints in your code when the test is running, and read out the variables. With this, you'll be able to tell if your tags are actually getting created, or if they're being ignored for some reason. (Or you can console log if you're taking a more roundabout approach)

See the following link for test examples:
https://github.com/Paperback-iOS/extensions-beta/tree/master/src/tests

If you are sure that the fields are being populated with tags, and they're simply not being shown, let me know and I can run a deeper review cycle. This is my knee-jerk thought on the matter, at least.

**Comment by getBoolean** [comment]
Thanks, I'll try using Mocha tests

**Comment by getBoolean** [comment]
Fixed, see #6
